### ISSUE TITLE
Add orElseThrow()

### ISSUE THREAD

**Issue by pivovarit** [jasongoodwin/better-java-monads#12]
I suggest adding orElseThrow() method that could be used to translate the thrown exception into an exception of your own choice.

What do you think?

**Comment by pivovarit** [comment]
orElseThrow(Function<Throwable, Exception> exception)
orElseThrow(Supplier<Exception> exception)

**Comment by jasongoodwin** [comment]
Not sure you need this. Can't you just use orElse and then get? I'll look at the API in java here shortly.

Eg in scala:

scala> scala.util.Try(throw new Exception("oops"))
res0: scala.util.Try[Nothing] = Failure(java.lang.Exception: oops)

scala> res0.orElse(throw new Exception("died")).get
java.lang.Exception: died
  at $anonfun$1.apply(<console>:9)
  at $anonfun$1.apply(<console>:9)
  at scala.util.Try.orElse(Try.scala:83)
  ... 33 elided

**Comment by jasongoodwin** [comment]
Actually, you just want the effect on failure so you can do this (unit test copied). Is this sufficient for your use case? I think this is exactly what you want to do, right?

    @Test(expected = IllegalArgumentException.class)
    public void itShouldThrowExceptionFromTryConsumerOnFailureIfFailure() throws Throwable {
        Try<String> t = Try.ofFailable(() -> {
            throw new IllegalArgumentException("Expected exception");
        });

        t.onFailure(s -> {
            throw new IllegalArgumentException("Should be thrown.");
        });
    }

**Comment by jasongoodwin** [comment]
you could also orElseTry and then get.

        Try<String> t = Try.ofFailable(() -> "hey").orElseTry(() -> throw new Exception).get;

If you think that the semantics of having orElseThrow would be useful, let me know. I'd like to look at a few use cases I guess.  More code is more to maintain and muddies the api - I think you can express this semantic already in a few ways.

**Comment by pivovarit** [comment]
The example with onFailure() is pretty much what I am looking for. Just thought about a shorthand to it.
orElseThrow() could be equal to:

```
final String string = someTry.onFailure(s -> {
            throw new IllegalArgumentException("Should be thrown.");
        }).get();
```

The problem with this is that get() bu default throws a checked Throwable, but this could be solved with using getUnchecked() from #11

**Comment by pivovarit** [comment]
Alternatively, you could use `toOptional().orElseThrow()` but in such case you can't access the cause

**Comment by jasongoodwin** [comment]
Okay cool. If the Java optional api has or else throw I'll look at this a bit more.

**Comment by jasongoodwin** [comment]
Targeting tomorrow.
I have a few bigger changes I'd like to make but I'll get this in with your other CL and publish probably this week.

**Comment by jasongoodwin** [comment]
k publishing 0.3.0. I'll updated the readme.

**Comment by jasongoodwin** [comment]
https://github.com/jasongoodwin/better-java-monads/commit/90b6f6227f527234f1d4ab48b4774dedfdb17018

**Comment by pivovarit** [comment]
Great :)
