### ISSUE TITLE
onSuccess/onFailure should not return the Try

### ISSUE THREAD

**Issue by jasongoodwin** [jasongoodwin/better-java-monads#13]
These take consumer functions as arguments and so the API is not explicit enough in returning the try again.
It looks nice chaining the effects together but I don't believe that the Try should be returned in these cases as it is not (and cannot) be mutated.

**Comment by greenbarbus** [comment]
imho it's very convenient feature to call "side action" from the chain... it would be a pity if chain is broken. may be just change the method name like passTryWithApplayngOnFailure or smth like this ?
