### ISSUE TITLE
Published POM adds dependency on scala-library-2.10.4

### ISSUE THREAD

**Issue by umcodemonkey** [jasongoodwin/better-java-monads#21]
Not sure why, but the published pom has a dependency on scala-library. See https://repo1.maven.org/maven2/com/jason-goodwin/better-monads/0.4.0/better-monads-0.4.0.pom. The dependency can be excluded without impact, but it should be removed if it is not needed.

**Comment by jasongoodwin** [comment]
Hmm. It's published via SBT - I'll investigate this a bit. Thanks for bringing this up.

**Comment by Joe0** [comment]
Any updates on this? I just ran into this issue as well, and was wondering if it will be fixed.

**Comment by jasongoodwin** [comment]
Thanks - I'll try to publish now.
