### ISSUE TITLE
Don't throw a checked exception on get of try

### ISSUE THREAD

**Issue by jasongoodwin** [jasongoodwin/better-java-monads#3]
Alex A says it should throw an unchecked exception on get.

**Comment by slnowak** [comment]
Or at least provide two methods - get and checkedGet or something similar.

**Comment by jasongoodwin** [comment]
that's true. Having:
- get which throws 
- and getUnchecked that wraps the exception in a runtime exception.

I think is the right way to do this - we want to make the effect of an exception explicit in the code - we should either say get that throws, or getUnchecked so you can see immediately in either the API or the code that there is an exception as an effect.
