### ISSUE TITLE
Fix project URL in pom

### ISSUE THREAD

**Issue by nicolaiparlog** [jasongoodwin/better-java-monads#9]
The project URL in [the generated pom](http://search.maven.org/#artifactdetails|com.jason-goodwin|better-monads|0.2.1|jar) links to http://jasongoodwin.com/better-java-monads. The missing dash sends people to another site, which [led to some confusion](https://twitter.com/nipafx/status/606726527070404608). :smiley:

**Comment by jasongoodwin** [comment]
Lol ya that's not me! Thanks for bringing this up.

**Comment by jasongoodwin** [comment]
Fixed. Thanks!
